# Generated by Django 4.2.30 on 2026-05-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_issue', models.TextField(help_text='The primary problem the user wants to address.')),
                ('issue_duration', models.CharField(help_text='How long this issue has persisted, e.g. "6 months", "10 years".', max_length=100)),
                ('triggers', models.JSONField(default=list, help_text='Situations or stimuli that trigger the problem. Stored as list of strings.')),
                ('symptoms', models.JSONField(default=list, help_text='Emotions and physical sensations experienced (labeled "emotions" in UI).')),
                ('behavior_to_change', models.TextField(help_text='The specific behaviour the user wants to modify.')),
                ('desired_emotional_shift', models.CharField(help_text='The emotional state the user wants to move toward.', max_length=200)),
                ('success_vision', models.TextField(help_text="The user's own description of life after the transformation.")),
                ('positive_anchoring_memory', models.TextField(help_text='A real positive memory used for NLP resource anchoring.')),
                ('interests', models.JSONField(default=list, help_text='Hobbies/interests used to build personalised metaphors. Stored as list of strings.')),
                ('work_life_environment', models.TextField(help_text="Description of the user's daily work and life context.")),
                ('repeating_thoughts', models.TextField(blank=True, help_text='Recurring negative thought patterns.')),
                ('negative_beliefs', models.TextField(blank=True, help_text='Core limiting beliefs identified by the user.')),
                ('has_inner_conflict', models.BooleanField(blank=True, help_text='Whether the user experiences conflicting motivations.', null=True)),
                ('inner_conflict_description', models.TextField(blank=True, help_text='Description of the inner conflict — enables Parts Therapy.')),
                ('resistance_protection', models.TextField(blank=True, help_text='What the resistant part is protecting the user against.')),
                ('body_location', models.CharField(blank=True, help_text='Where in the body the emotion is felt — enables Somatic Release.', max_length=100)),
                ('representational_system', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('kinesthetic', 'Kinesthetic')], help_text='Primary NLP sensory channel — determines language style of suggestions.', max_length=20)),
                ('fears_about_change', models.TextField(blank=True, help_text='What the user fears might happen if they change.')),
                ('connected_to_past_event', models.BooleanField(blank=True, help_text='Whether the issue connects to a past event — enables Timeline Therapy.', null=True)),
                ('key_affirmations', models.JSONField(blank=True, default=list, help_text='User-supplied affirmations for identity-level installation. Stored as list of strings.')),
                ('language_to_avoid', models.JSONField(blank=True, default=list, help_text='Words or phrases the AI must not use (trauma-sensitive care). Stored as list of strings.')),
                ('session_duration_minutes', models.PositiveIntegerField(help_text='Requested session length in minutes (10-45).')),
                ('focus_category', models.CharField(blank=True, help_text='Optional override for focus area.', max_length=100)),
                ('post_session_state', models.CharField(choices=[('sleep', 'Drift to sleep'), ('alert', 'Wake alert')], default='alert', help_text='Whether session ends with sleep induction or alert emergence.', max_length=20)),
                ('problem_category', models.CharField(blank=True, help_text='Auto-diagnosed problem category (sleep, anxiety, trauma, etc.).', max_length=50)),
            ],
            options={
                'verbose_name': 'Intake Response',
                'verbose_name_plural': 'Intake Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
