# Generated by Django 5.1.15 on 2026-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeresponse',
            name='behavior_to_change',
            field=models.TextField(blank=True, default='', help_text='The specific behaviour the user wants to modify.'),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='desired_emotional_shift',
            field=models.CharField(blank=True, default='', help_text='The emotional state the user wants to move toward.', max_length=200),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='Hobbies/interests used to build personalised metaphors. Stored as list of strings.'),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='issue_duration',
            field=models.CharField(blank=True, default='', help_text='How long this issue has persisted, e.g. "6 months", "10 years".', max_length=100),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='main_issue',
            field=models.TextField(blank=True, default='', help_text='The primary problem the user wants to address.'),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='positive_anchoring_memory',
            field=models.TextField(blank=True, default='', help_text='A real positive memory used for NLP resource anchoring.'),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='session_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Requested session length in minutes (10-45).', null=True),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='success_vision',
            field=models.TextField(blank=True, default='', help_text="The user's own description of life after the transformation."),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='symptoms',
            field=models.JSONField(blank=True, default=list, help_text='Emotions and physical sensations experienced (labeled "emotions" in UI).'),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='triggers',
            field=models.JSONField(blank=True, default=list, help_text='Situations or stimuli that trigger the problem. Stored as list of strings.'),
        ),
        migrations.AlterField(
            model_name='intakeresponse',
            name='work_life_environment',
            field=models.TextField(blank=True, default='', help_text="Description of the user's daily work and life context."),
        ),
    ]
