# Generated by Django 4.2.30 on 2026-05-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('minutes', models.PositiveIntegerField(help_text='Number of session minutes included.')),
                ('price_cents', models.PositiveIntegerField(help_text='Price in cents (e.g. 999 = $9.99).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Credit Package',
                'verbose_name_plural': 'Credit Packages',
                'ordering': ['sort_order', 'price_cents'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('free_allocation', 'Free Allocation'), ('purchase', 'Purchase'), ('session_use', 'Session Use'), ('refund', 'Refund'), ('bonus', 'Bonus')], db_index=True, max_length=20)),
                ('minutes_amount', models.IntegerField(help_text='Positive = credit added, Negative = credit used.')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
