# Generated by Django 4.2.30 on 2026-05-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_before', models.PositiveSmallIntegerField(help_text='Mood score before the session (1-10).')),
                ('mood_after', models.PositiveSmallIntegerField(blank=True, help_text='Mood score after the session (1-10). Filled in post-session.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effectiveness_rating', models.PositiveSmallIntegerField(help_text='Overall effectiveness rating (1-5).')),
                ('techniques_resonated', models.JSONField(blank=True, default=list, help_text='List of technique names the user found particularly effective.')),
                ('techniques_to_adjust', models.JSONField(blank=True, default=list, help_text='Techniques the user wants de-emphasised in future sessions.')),
                ('general_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Session Feedback',
                'verbose_name_plural': 'Session Feedback',
            },
        ),
        migrations.CreateModel(
            name='TherapeuticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('most_effective_techniques', models.JSONField(default=list, help_text='Techniques consistently rated highly by this user.')),
                ('least_effective_techniques', models.JSONField(default=list, help_text='Techniques to de-emphasise.')),
                ('average_mood_improvement_by_category', models.JSONField(default=dict, help_text='Average mood delta grouped by problem_category.')),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('key_themes', models.JSONField(default=list, help_text='Recurring themes extracted from feedback notes.')),
            ],
            options={
                'verbose_name': 'Therapeutic Profile',
                'verbose_name_plural': 'Therapeutic Profiles',
            },
        ),
    ]
