# Generated by Django 4.2.30 on 2026-05-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('focus_technique', models.CharField(blank=True, help_text='Primary therapeutic technique for this day.', max_length=100)),
            ],
            options={
                'verbose_name': 'Program Day',
                'verbose_name_plural': 'Program Days',
                'ordering': ['program', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='TherapyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_days', models.PositiveIntegerField()),
                ('category', models.CharField(help_text='Problem category this program targets (sleep, anxiety, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Therapy Program',
                'verbose_name_plural': 'Therapy Programs',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.therapyprogram')),
            ],
            options={
                'verbose_name': 'User Program Enrollment',
                'verbose_name_plural': 'User Program Enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
