# Generated by Django 4.2.30 on 2026-05-17 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogramenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.therapyprogram'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogramenrollment',
            unique_together={('user', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program', 'day_number')},
        ),
    ]
