# Generated by Django 4.2.30 on 2026-05-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_key', models.CharField(help_text='S3/Spaces object key.', max_length=500)),
                ('cdn_url', models.URLField(help_text='Public CDN URL.')),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(default='mp3', max_length=10)),
            ],
            options={
                'verbose_name': 'Audio Asset',
                'verbose_name_plural': 'Audio Assets',
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating_script', 'Generating Script'), ('generating_audio', 'Generating Audio'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=25)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('credits_used', models.PositiveIntegerField()),
                ('script_text', models.TextField(blank=True, help_text='Full raw script returned by Claude.')),
                ('script_chunks', models.JSONField(blank=True, default=list, help_text='Array of text chunks sent to ElevenLabs TTS.')),
                ('audio_url', models.URLField(blank=True, help_text='Public CDN URL of the final MP3 file.')),
                ('audio_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Populated if status=failed.')),
                ('techniques_used', models.JSONField(blank=True, default=list, help_text='NLP/hypnotherapy techniques auto-selected for this session.')),
                ('problem_category', models.CharField(blank=True, max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='intake.intakeresponse')),
                ('program_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='programs.programday')),
            ],
            options={
                'verbose_name': 'Therapy Session',
                'verbose_name_plural': 'Therapy Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
