# Generated by Django 5.1.15 on 2026-06-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='language',
            field=models.CharField(default='en', help_text='Target language for the session (e.g., en, es, fr)', max_length=10),
        ),
    ]
